import type { AdvancedModuleDefinition, AdvancedModuleId } from "./types";

export const ADVANCED_MODULE_REGISTRY: AdvancedModuleDefinition[] = [
  {
    id: "strategy-registry",
    label: "Strategy Registry",
    href: "/strategies",
    description: "Strategy skill registry — statuses feed analyze payload and committee gates.",
    role: "analysis_input",
    engineReads: true,
    contextField: "strategyRegistry",
    relatedEventTypes: ["GOVERNANCE_CHECKED", "VERDICT_CREATED", "REPORT_UPDATED"],
  },
  {
    id: "governance",
    label: "Governance",
    href: "/governance",
    description: "Safe mode, hard rules, and operator pause — can block analysis and trades.",
    role: "analysis_input",
    engineReads: true,
    contextField: "governance",
    relatedEventTypes: ["GOVERNANCE_CHECKED", "BLOCKER_CREATED", "BLOCKER_RESOLVED"],
  },
  {
    id: "validation",
    label: "Validation",
    href: "/validation",
    description: "Kill switch and performance matrix — feeds risk gate and validation blockers.",
    role: "analysis_input",
    engineReads: true,
    contextField: "validation",
    relatedEventTypes: ["RISK_CHECKED", "BLOCKER_CREATED", "READINESS_CHECKED"],
  },
  {
    id: "council",
    label: "Council",
    href: "/council",
    description: "Multi-agent committee — weighted verdict attached during playbook analyze.",
    role: "analysis_input",
    engineReads: true,
    contextField: "councilState",
    relatedEventTypes: ["AGENTS_REVIEWED", "VERDICT_CREATED"],
  },
  {
    id: "simulation",
    label: "Simulation",
    href: "/simulation",
    description: "Capital risk and rule impact simulators — advisory, does not auto-trade.",
    role: "advisory",
    engineReads: true,
    contextField: "simulationState",
    relatedEventTypes: ["REPORT_UPDATED"],
  },
  {
    id: "war-room",
    label: "War Room",
    href: "/war-room",
    description: "Operator discipline drills and scenario playbook — advisory review only.",
    role: "advisory",
    engineReads: false,
    contextField: null,
    relatedEventTypes: ["BLOCKER_CREATED", "READINESS_CHECKED"],
  },
  {
    id: "incidents",
    label: "Incidents",
    href: "/incidents",
    description: "Desk incidents and post-mortems — open critical incidents block analysis.",
    role: "analysis_input",
    engineReads: true,
    contextField: "incidentState",
    relatedEventTypes: ["BLOCKER_CREATED", "REPORT_UPDATED"],
  },
  {
    id: "capital",
    label: "Capital",
    href: "/capital",
    description: "Mission capital stages and planning — advisory mission context only.",
    role: "advisory",
    engineReads: false,
    contextField: null,
    relatedEventTypes: ["REPORT_UPDATED"],
  },
  {
    id: "automation",
    label: "Automation",
    href: "/automation",
    description: "Desk automation cycles — triggers central engine via DESK_ANALYZE jobs.",
    role: "analysis_input",
    engineReads: true,
    contextField: "simulationState.lastRunAt",
    relatedEventTypes: ["ANALYSIS_STARTED", "CONTEXT_BUILT", "VERDICT_CREATED"],
  },
  {
    id: "api-docs",
    label: "API Docs",
    href: "/api-docs",
    description: "HTTP API contract reference — metadata for integrators.",
    role: "metadata",
    engineReads: false,
    contextField: null,
    relatedEventTypes: [],
  },
  {
    id: "ledger",
    label: "Raw Ledger",
    href: "/ledger",
    description: "Unified decision and trade ledger — audit trail, not analyze input.",
    role: "metadata",
    engineReads: false,
    contextField: null,
    relatedEventTypes: ["ORDER_EXECUTED", "POSITION_CLOSED", "PNL_REALIZED"],
  },
  {
    id: "debug",
    label: "Debug",
    href: "/testnet-monitor",
    description: "Testnet monitor, Binance debug, and monitor journal — connectivity checks.",
    role: "advisory",
    engineReads: true,
    contextField: "testnetStatus",
    relatedEventTypes: ["PREVIEW_CREATED", "ORDER_EXECUTED", "POSITION_MONITORED"],
  },
];

export function getAdvancedModuleDefinition(
  id: AdvancedModuleId,
): AdvancedModuleDefinition | undefined {
  return ADVANCED_MODULE_REGISTRY.find((m) => m.id === id);
}

export function listAdvancedModuleDefinitions(): AdvancedModuleDefinition[] {
  return [...ADVANCED_MODULE_REGISTRY];
}
