"use client";

import { useCallback, useEffect, useState } from "react";
import OpsShell from "@/components/ops/OpsShell";
import { loadDecisionLog } from "@/lib/journal/decision-log";
import { loadPaperOrders } from "@/lib/paper/paper-orders";
import { loadPerpPositions } from "@/lib/multi-asset/perp-paper-store";
import { loadDeskSettings } from "@/lib/desk/desk-settings";
import { buildStrategyRegistry } from "@/lib/strategy-registry/build-strategy-registry";
import type {
  AdaptationAnalysisResult,
  AdaptationAuditEntry,
  StrategyAdaptationProposal,
} from "@/lib/strategy-adaptation/types";
import { loadBacktestAdaptationBridge } from "@/lib/historical-backtest/client-bridge";
import {
  appendAdaptationAudit,
  loadAdaptationAuditLog,
  loadAdaptationProposals,
  mergeAdaptationProposals,
  persistApplyResult,
} from "@/lib/strategy-adaptation/proposal-store";

function typeBadge(type: StrategyAdaptationProposal["type"]): string {
  const map: Record<string, string> = {
    PROMOTE: "bg-emerald-900/50 text-emerald-200",
    DEMOTE: "bg-rose-900/50 text-rose-200",
    PAUSE: "bg-orange-900/50 text-orange-200",
    TIGHTEN_RULE: "bg-amber-900/50 text-amber-200",
    RELAX_RULE: "bg-cyan-900/50 text-cyan-200",
    REVIEW_ONLY: "bg-zinc-800 text-zinc-300",
  };
  return map[type] ?? "bg-zinc-800 text-zinc-300";
}

export default function AdaptationDashboard() {
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [analysis, setAnalysis] = useState<AdaptationAnalysisResult | null>(null);
  const [proposals, setProposals] = useState<StrategyAdaptationProposal[]>([]);
  const [audit, setAudit] = useState<AdaptationAuditEntry[]>([]);
  const [editNotes, setEditNotes] = useState<Record<string, string>>({});

  const refreshLocal = useCallback(() => {
    setProposals(loadAdaptationProposals());
    setAudit(loadAdaptationAuditLog());
  }, []);

  const runAnalyze = useCallback(async () => {
    setBusy(true);
    setError(null);
    const entries = loadDecisionLog();
    const orders = loadPaperOrders();
    const riskProfile = loadDeskSettings().riskProfile;
    try {
      const res = await fetch("/api/strategy-adaptation/analyze", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          entries,
          orders,
          perpPositions: loadPerpPositions(),
          riskProfile,
          historicalBacktest: loadBacktestAdaptationBridge(),
        }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error ?? res.statusText);
      setAnalysis(data as AdaptationAnalysisResult);
      const merged = mergeAdaptationProposals(data.proposals ?? []);
      setProposals(merged);
      for (const p of data.proposals ?? []) {
        appendAdaptationAudit({
          id: `audit-create-${p.proposalId}`,
          timestamp: new Date().toISOString(),
          proposalId: p.proposalId,
          action: "CREATED",
          operatorNote: "Generated by adaptation engine",
          targetStrategy: p.targetStrategy,
          proposalType: p.type,
          beforeStatus: p.previousRegistryStatus,
          afterStatus: p.proposedRegistryStatus,
          reversible: true,
        });
      }
      refreshLocal();
    } catch (e) {
      setError(e instanceof Error ? e.message : "Analyze failed");
    } finally {
      setBusy(false);
    }
  }, [refreshLocal]);

  const runAction = async (
    proposal: StrategyAdaptationProposal,
    action: "approve" | "reject" | "edit" | "apply" | "revert",
  ) => {
    setBusy(true);
    setError(null);
    const registry = buildStrategyRegistry({
      entries: loadDecisionLog(),
      orders: loadPaperOrders(),
      riskProfile: loadDeskSettings().riskProfile,
    });
    try {
      const res = await fetch("/api/strategy-adaptation/apply", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          proposalId: proposal.proposalId,
          action,
          proposal,
          registry,
          operatorNote: editNotes[proposal.proposalId] ?? "",
          editedReason: editNotes[proposal.proposalId],
        }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error ?? res.statusText);
      persistApplyResult(data);
      refreshLocal();
    } catch (e) {
      setError(e instanceof Error ? e.message : "Action failed");
    } finally {
      setBusy(false);
    }
  };

  useEffect(() => {
    refreshLocal();
  }, [refreshLocal]);

  const report = analysis?.report;
  const queue = proposals.filter(
    (p) => p.status === "PENDING" || p.status === "APPROVED",
  );

  return (
    <OpsShell
      badge="MVP 24 · Human approval"
      title="Strategy Adaptation"
      subtitle="Reviews paper outcomes and proposes registry changes — never auto-applies, never enables live execution."
      accent="indigo"
      iconLetters="AD"
      activePath="/adaptation"
      nav={[
        { href: "/", label: "← Desk" },
        { href: "/strategies", label: "Registry", primary: true },
        { href: "/council", label: "Council" },
        { href: "/portfolio", label: "Portfolio" },
      ]}
      actions={
        <button
          type="button"
          disabled={busy}
          onClick={() => void runAnalyze()}
          className="rounded-lg bg-indigo-700/90 px-4 py-2 text-xs font-semibold text-zinc-100 disabled:opacity-50"
        >
          {busy ? "Analyzing…" : "Run adaptation analysis"}
        </button>
      }
    >
      <p className="rounded-lg border border-indigo-900/40 bg-indigo-950/20 px-4 py-2 text-xs text-indigo-200/80">
        {analysis?.safetyNotice ??
          "All proposals require human approval. Changes are reversible via audit log."}
      </p>
      {error && <p className="text-sm text-rose-400">{error}</p>}

      {report && (
        <>
          <section className="desk-panel px-5 py-4">
            <h2 className="text-sm font-semibold text-zinc-100">
              Strategy Performance Table
            </h2>
            <div className="mt-3 overflow-x-auto">
              <table className="w-full min-w-[640px] text-left text-xs">
                <thead>
                  <tr className="border-b border-zinc-800 text-[10px] uppercase text-zinc-500">
                    <th className="py-2 pr-3">Strategy</th>
                    <th className="py-2 pr-3">Status</th>
                    <th className="py-2 pr-3">Win%</th>
                    <th className="py-2 pr-3">Avg PnL</th>
                    <th className="py-2 pr-3">Max DD</th>
                    <th className="py-2">N</th>
                  </tr>
                </thead>
                <tbody>
                  {report.strategyPerformance.map((row) => (
                    <tr key={row.strategyId} className="border-b border-zinc-900 text-zinc-300">
                      <td className="py-2 pr-3">{row.label}</td>
                      <td className="py-2 pr-3 font-mono text-[10px]">{row.currentStatus}</td>
                      <td className="py-2 pr-3">{row.winRate}%</td>
                      <td className="py-2 pr-3">{row.avgPnlPct}%</td>
                      <td className="py-2 pr-3">{row.maxDrawdownPct}%</td>
                      <td className="py-2">{row.sampleSize}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </section>

          <div className="grid gap-4 lg:grid-cols-2">
            <section className="desk-panel px-5 py-4">
              <h2 className="text-sm font-semibold text-zinc-100">Regime Performance</h2>
              <ul className="mt-3 space-y-2 text-xs text-zinc-400">
                {report.regimePerformance.length === 0 ? (
                  <li>No resolved regime samples yet.</li>
                ) : (
                  report.regimePerformance.map((r) => (
                    <li key={r.regime}>
                      <span className="font-medium text-zinc-200">{r.regime}</span> —{" "}
                      {r.winRate}% win · n={r.sampleSize}
                      {r.bestStrategy && (
                        <span className="text-emerald-400/80">
                          {" "}
                          · best {r.bestStrategy}
                        </span>
                      )}
                    </li>
                  ))
                )}
              </ul>
            </section>

            <section className="desk-panel px-5 py-4">
              <h2 className="text-sm font-semibold text-zinc-100">Agent Accuracy</h2>
              <ul className="mt-3 space-y-2 text-xs text-zinc-400">
                {report.agentAccuracy.slice(0, 8).map((a) => (
                  <li key={a.agentName}>
                    {a.agentName}: {a.accuracyPct}% ({a.totalCalls} calls)
                  </li>
                ))}
              </ul>
              <p className="mt-3 text-[10px] text-zinc-500">
                Strict paper: {report.strictVsRelaxed.strict.trades} trades ·{" "}
                {report.strictVsRelaxed.strict.winRate}% win · Relaxed:{" "}
                {report.strictVsRelaxed.relaxed.trades} trades ·{" "}
                {report.strictVsRelaxed.relaxed.winRate}% win
              </p>
            </section>
          </div>
        </>
      )}

      <section className="desk-panel px-5 py-4">
        <h2 className="text-sm font-semibold text-zinc-100">Proposed Changes</h2>
        {proposals.length === 0 ? (
          <p className="mt-2 text-xs text-zinc-500">
            Run analysis to generate proposals from paper outcomes.
          </p>
        ) : (
          <ul className="mt-3 space-y-3">
            {proposals.map((p) => (
              <li
                key={p.proposalId}
                className="rounded-lg border border-zinc-800 bg-zinc-950/50 px-4 py-3"
              >
                <div className="flex flex-wrap items-center gap-2">
                  <span
                    className={`rounded px-2 py-0.5 text-[10px] font-bold uppercase ${typeBadge(p.type)}`}
                  >
                    {p.type}
                  </span>
                  <span className="text-xs font-semibold text-zinc-200">
                    {p.targetStrategy}
                  </span>
                  <span className="text-[10px] text-zinc-500">
                    conf {p.confidence}% · {p.status}
                  </span>
                </div>
                <p className="mt-1 text-xs text-zinc-400">{p.reason}</p>
                <p className="mt-1 text-[10px] text-zinc-500">{p.expectedBehaviorChange}</p>
                {p.proposedRegistryStatus && (
                  <p className="text-[10px] text-indigo-300/80">
                    → {p.previousRegistryStatus} to {p.proposedRegistryStatus}
                  </p>
                )}
                <textarea
                  className="mt-2 w-full rounded border border-zinc-700 bg-zinc-950 px-2 py-1 text-[10px] text-zinc-300"
                  placeholder="Operator note / edit reason"
                  value={editNotes[p.proposalId] ?? ""}
                  onChange={(e) =>
                    setEditNotes((prev) => ({
                      ...prev,
                      [p.proposalId]: e.target.value,
                    }))
                  }
                />
                <div className="mt-2 flex flex-wrap gap-2">
                  {p.status === "PENDING" && (
                    <>
                      <button
                        type="button"
                        disabled={busy}
                        onClick={() => void runAction(p, "approve")}
                        className="rounded bg-emerald-800/80 px-2 py-1 text-[10px] font-semibold text-zinc-100"
                      >
                        Approve
                      </button>
                      <button
                        type="button"
                        disabled={busy}
                        onClick={() => void runAction(p, "reject")}
                        className="rounded bg-rose-900/80 px-2 py-1 text-[10px] font-semibold text-zinc-100"
                      >
                        Reject
                      </button>
                      <button
                        type="button"
                        disabled={busy}
                        onClick={() => void runAction(p, "edit")}
                        className="rounded border border-zinc-600 px-2 py-1 text-[10px] text-zinc-300"
                      >
                        Save edit
                      </button>
                    </>
                  )}
                  {(p.status === "APPROVED" || p.status === "PENDING") && (
                    <button
                      type="button"
                      disabled={busy}
                      onClick={() => void runAction(p, "apply")}
                      className="rounded bg-indigo-700/90 px-2 py-1 text-[10px] font-semibold text-zinc-100"
                    >
                      Apply to registry
                    </button>
                  )}
                  {p.status === "APPLIED" && p.previousRegistryStatus && (
                    <button
                      type="button"
                      disabled={busy}
                      onClick={() => void runAction(p, "revert")}
                      className="rounded border border-amber-700/50 px-2 py-1 text-[10px] text-amber-200"
                    >
                      Revert
                    </button>
                  )}
                </div>
              </li>
            ))}
          </ul>
        )}
      </section>

      <section className="desk-panel px-5 py-4">
        <h2 className="text-sm font-semibold text-zinc-100">Approval Queue</h2>
        <p className="mt-1 text-xs text-zinc-500">
          {queue.length} pending / approved awaiting apply
        </p>
        {queue.length > 0 && (
          <ul className="mt-3 space-y-2 text-xs text-zinc-400">
            {queue.map((p) => (
              <li
                key={`queue-${p.proposalId}`}
                className="flex flex-wrap items-center gap-2 rounded border border-zinc-800 px-3 py-2"
              >
                <span
                  className={`rounded px-1.5 py-0.5 text-[9px] font-bold uppercase ${typeBadge(p.type)}`}
                >
                  {p.type}
                </span>
                <span className="font-medium text-zinc-200">{p.targetStrategy}</span>
                <span className="text-[10px] text-zinc-500">{p.status}</span>
              </li>
            ))}
          </ul>
        )}
      </section>

      <section className="desk-panel px-5 py-4">
        <h2 className="text-sm font-semibold text-zinc-100">Audit Log</h2>
        {audit.length === 0 ? (
          <p className="mt-2 text-xs text-zinc-500">No audit entries yet.</p>
        ) : (
          <ul className="mt-3 max-h-64 space-y-1 overflow-y-auto text-[10px] text-zinc-500">
            {audit.map((a) => (
              <li key={a.id}>
                {new Date(a.timestamp).toLocaleString()} · {a.action} ·{" "}
                {a.targetStrategy} · {a.proposalType}
                {a.beforeStatus && a.afterStatus && (
                  <span>
                    {" "}
                    ({a.beforeStatus}→{a.afterStatus})
                  </span>
                )}
              </li>
            ))}
          </ul>
        )}
      </section>
    </OpsShell>
  );
}
