# Interactive testnet setup — creates .env.local and opens Bybit testnet API page.
# Usage: powershell -ExecutionPolicy Bypass -File scripts/setup-testnet.ps1

$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$EnvFile = Join-Path $Root ".env.local"
$ExampleFile = Join-Path $Root ".env.example"

function New-RandomSecret {
    return -join ((48..57) + (65..90) + (97..122) | Get-Random -Count 32 | ForEach-Object { [char]$_ })
}

Write-Host ""
Write-Host "=== BTC Desk — Testnet setup wizard ===" -ForegroundColor Cyan
Write-Host ""

if (Test-Path $EnvFile) {
    Write-Host "Found existing .env.local — will merge (keeps existing values if you press Enter)." -ForegroundColor Yellow
    Get-Content $EnvFile | ForEach-Object {
        if ($_ -match '^\s*([A-Za-z_][A-Za-z0-9_]*)=(.*)$') {
            $k = $Matches[1]
            $v = $Matches[2].Trim().Trim('"')
            if (-not [string]::IsNullOrWhiteSpace($v) -and $v -notmatch '^your-|^xxx|^paste') {
                Set-Variable -Name "EXIST_$k" -Value $v -Scope Script
            }
        }
    }
}

$existingKey = $script:EXIST_BYBIT_API_KEY
$existingSecret = $script:EXIST_BYBIT_API_SECRET
$existingCron = $script:EXIST_CRON_SECRET

Write-Host ""
Write-Host "Step 1: Bybit TESTNET API keys" -ForegroundColor Green
Write-Host "  Open: https://testnet.bybit.com/app/user/api-management"
Write-Host "  Permissions: Read + Trade (no Withdraw)"
Write-Host ""

$openBrowser = Read-Host "Open testnet API page in browser now? [Y/n]"
if ($openBrowser -ne "n" -and $openBrowser -ne "N") {
    Start-Process "https://testnet.bybit.com/app/user/api-management"
}

Write-Host ""
$apiKey = Read-Host "BYBIT_API_KEY (testnet)"
if ([string]::IsNullOrWhiteSpace($apiKey)) { $apiKey = $existingKey }

$apiSecret = Read-Host "BYBIT_API_SECRET (testnet, hidden)"
if ([string]::IsNullOrWhiteSpace($apiSecret)) { $apiSecret = $existingSecret }
if ([string]::IsNullOrWhiteSpace($apiSecret) -and $existingSecret) { $apiSecret = $existingSecret }

$cronSecret = $existingCron
if ([string]::IsNullOrWhiteSpace($cronSecret)) {
    $cronSecret = New-RandomSecret
    Write-Host "Generated CRON_SECRET (auto)" -ForegroundColor DarkGray
}

$maxNotional = Read-Host "LIVE_MAX_NOTIONAL_USD [50]"
if ([string]::IsNullOrWhiteSpace($maxNotional)) { $maxNotional = "50" }

$symbols = Read-Host "LIVE_ALLOWED_SYMBOLS [BTCUSDT,SOLUSDT,DOGEUSDT] (Enter = default)"
if ([string]::IsNullOrWhiteSpace($symbols)) { $symbols = "BTCUSDT,SOLUSDT,DOGEUSDT" }

$lines = @(
    "# BTC Desk — testnet (generated by setup-testnet.ps1)",
    "# Keys MUST be from https://testnet.bybit.com — NOT mainnet",
    "",
    "CRON_SECRET=$cronSecret",
    "",
    "BYBIT_API_KEY=$apiKey",
    "BYBIT_API_SECRET=$apiSecret",
    "BYBIT_TESTNET=true",
    "",
    "LIVE_EXECUTION_ENABLED=true",
    "LIVE_REQUIRE_DOUBLE_CONFIRM=true",
    "LIVE_MAX_NOTIONAL_USD=$maxNotional",
    "LIVE_ALLOWED_SYMBOLS=$symbols",
    "",
    "# Optional alerts",
    "# TELEGRAM_BOT_TOKEN=",
    "# TELEGRAM_CHAT_ID=",
    "# SUPABASE_URL=",
    "# SUPABASE_SERVICE_ROLE_KEY=",
    ""
)

Set-Content -Path $EnvFile -Value ($lines -join "`n") -Encoding UTF8
Write-Host ""
Write-Host "Wrote $EnvFile" -ForegroundColor Green

Write-Host ""
Write-Host "Step 2: Verify connection…" -ForegroundColor Green
Push-Location $Root
node scripts/verify-testnet-setup.mjs
$verifyExit = $LASTEXITCODE
Pop-Location

if ($verifyExit -eq 0) {
    Write-Host ""
    Write-Host "Step 3: Push to Vercel? Run when ready:" -ForegroundColor Green
    Write-Host "  powershell -ExecutionPolicy Bypass -File scripts/push-vercel-env.ps1"
    Write-Host ""
    $startDev = Read-Host "Start npm run dev now? [Y/n]"
    if ($startDev -ne "n" -and $startDev -ne "N") {
        Push-Location $Root
        npm run dev
    }
}
